summary: Add new opensuse 42.2 64 bits image to google account

environment:
    BUCKET_NAME: spread-images
    IMAGE_FILE: opensuse-leap-42-2-64
    IMAGE_URL: http://download.opensuse.org/repositories/Cloud:/Images:/Leap_42.2/images/leap42.1-guest-gce-0.0.13-Build1.19.tar.gz
    IMAGE: opensuse-leap-42-2-64-v$(date +'%Y%m%d')
    FAMILY: opensuse-leap-42-2-64
    DESCRIPTION: Opensuse leap 42.2 64 bits
    DISK: $(hostname)    

execute: |
    . "$TESTSLIB/google.sh"

    # Get the image
    wget -O "${IMAGE_FILE}.tar.gz" "$IMAGE_URL"

    # Copy opensuse image to spread-images bucket
    gsutil cp "${IMAGE_FILE}.tar.gz" "gs://${BUCKET_NAME}/"
    
    # Create the image in computeengine project
    delete_image "$IMAGE"
    create_image_from_bucket "$IMAGE" "$FAMILY" "$DESCRIPTION" "${IMAGE_FILE}.tar.gz"

restore: |
    rm -f "${IMAGE_FILE}.tar.gz"
