summary: Add new opensuse 42.2 64 bits image to google account

environment:
    TARGET_SYSTEM: opensuse-42.2-64-base
    IMAGE_FILE: opensuse-leap-42-2-64
    IMAGE_URL: http://download.opensuse.org/repositories/Cloud:/Images:/Leap_42.2/images/leap42.1-guest-gce-0.0.13-Build1.23.tar.gz    

execute: |
    . "$TESTSLIB/google.sh"
    . "$TESTSLIB/names.sh"

    # Get the image
    wget -O "${IMAGE_FILE}.tar.gz" "$IMAGE_URL"

    # Copy opensuse image to spread-images bucket
    gsutil cp "${IMAGE_FILE}.tar.gz" "gs://${BUCKET_NAME}/"
    
    # Create the image in computeengine project
    delete_image "$IMAGE"
    create_image_from_bucket "$IMAGE" "$FAMILY" "$DESCRIPTION" "${IMAGE_FILE}.tar.gz"

restore: |
    rm -f "${IMAGE_FILE}.tar.gz"
