summary: Update Debian sid 64 bits image with the latest updates

systems: [debian-sid-64]

environment:
    IMAGE: debian-sid-64-v$(date +'%Y%m%d')
    FAMILY: debian-sid-64
    DESCRIPTION: Debian Sid 64 bits
    DISK: $(hostname)

execute: |
    . "$TESTSLIB/google.sh"
    . "$TESTSLIB/pkgdb.sh"
    . "$TESTSLIB/utils.sh"

    # We are not making dist-upgrade because it is creating a dependencies issue
    # which is making fail the preparation of the snapd test suite 
    if [ "$SPREAD_REBOOT" = 0 ]; then
        # Make the upgrade
        distro_update_package_db
        apt-get upgrade -y
        distro_clean_package_cache
        REBOOT
    fi

    # Clean disk before create the shapshot
    clean_machine

    # Create a new image based on the current disk
    create_image_from_disk "$IMAGE" "$FAMILY" "$DESCRIPTION" "$DISK"

restore: |
    . "$TESTSLIB/google.sh"

    delete_snapshot "$DISK"
