summary: Update fedora base image with the latest updates

systems: [fedora-30-64-base]

environment:
    TARGET_SYSTEM: fedora-30-64-base

execute: |
    . "$TESTSLIB/google.sh"
    . "$TESTSLIB/names.sh"
    . "$TESTSLIB/pkgdb.sh"
    . "$TESTSLIB/utils.sh"

    if [ "$SPREAD_REBOOT" = 0 ]; then
        distro_update_package_db
        distro_upgrade_packages
        distro_clean_package_cache

        # Disable cloud init because reset sshd config affecting spread metadata script
        # Also in fedora 30 cloud-init fails on start
        touch /etc/cloud/cloud-init.disabled

        REBOOT
    fi

    # Purge old kernel-core package
    pkgs=$(rpm -qa kernel-core)
    if [ $(echo "$pkgs" | wc -w) -gt 1 ]; then
        pkg=$(echo $pkgs | cut --delimiter " " --fields 2)
        distro_purge_package "$pkg"
    fi

    # Purge conflicting packages
    distro_purge_package whois-mkpasswd

    # Clean disk before create the shapshot
    clean_machine

    # Create a new image based on the current disk
    create_image_from_disk "$IMAGE" "$FAMILY" "$DESCRIPTION" "$DISK"

restore: |
    . "$TESTSLIB/google.sh"
    . "$TESTSLIB/names.sh"

    delete_snapshot "$DISK"
    delete_deprecated_images
