summary: Update fedora image with the latest updates and test dependencies with selinux permissive

systems: [fedora-30-64-base]

environment:
    TARGET_SYSTEM: fedora-30-64

execute: |
    . "$TESTSLIB/google.sh"
    . "$TESTSLIB/names.sh"
    . "$TESTSLIB/pkgdb.sh"
    . "$TESTSLIB/utils.sh"

    if [ "$SPREAD_REBOOT" = 0 ]; then
        # Make the upgrade and install the dependencies needed to run snapd tests
        distro_update_package_db
        distro_install_package kernel-modules
        distro_upgrade_packages
        install_test_dependencies "$TARGET_SYSTEM"
        remove_pkg_blacklist
        distro_clean_package_cache

        REBOOT
    fi

    # Purge old kernel-core package
    pkgs=$(rpm -qa kernel-core)
    if [ $(echo "$pkgs" | wc -w) -gt 1 ]; then
        pkg=$(echo $pkgs | cut --delimiter " " --fields 2)
        distro_purge_package "$pkg"
    fi

    # Set selinux as permissive
    sed -i 's/SELINUX=.*/SELINUX=permissive/g' /etc/selinux/config

    # Clean disk before create the shapshot
    clean_machine

    # Create a new image based on the current disk
    create_image_from_disk "$IMAGE" "$FAMILY" "$DESCRIPTION" "$DISK"

restore: |
    . "$TESTSLIB/google.sh"
    . "$TESTSLIB/names.sh"
    
    delete_snapshot "$DISK"
    delete_deprecated_images