summary: Create images and share them on the instance thought http server

systems: [ubuntu-16.04-64*, ubuntu-18.04-64*]

environment:
    IMAGE_CHANNEL: "$(HOST: echo ${SPREAD_IMAGE_CHANNEL:-beta})"
    IMAGE_PLATFORM: "$(HOST: echo ${SPREAD_IMAGE_PLATFORM:-})"

prepare: |
    apt install -y ubuntu-image

execute: |
    git clone https://github.com/sergiocazzolato/validator.git

    case "$SPREAD_SYSTEM" in
        ubuntu-16.04-64*)
            ( cd validator && ./create.sh "$IMAGE_CHANNEL" 16 "$IMAGE_PLATFORM" )
        ;;
        ubuntu-18.04-64*)
            ( cd validator && ./create.sh "$IMAGE_CHANNEL" 18 "$IMAGE_PLATFORM" )
        ;;
        *)
            echo "System not supported"
            exit 1
        ;;
    esac

    python -m SimpleHTTPServer 80
