summary: Add new arch linux image to google account

systems: [ubuntu-*]

environment:
    TARGET_SYSTEM: arch-linux-64-base
    IMAGE_FILE: arch-v4.14.12

execute: |
    . "$TESTSLIB/google.sh"
    . "$TESTSLIB/names.sh"

    # Download arch linux image from arch_linux bucket
    gsutil cp "gs://arch_linux/${IMAGE_FILE}.tar.gz" "${IMAGE_FILE}.tar.gz"
    
    # Upload arch linux image to spread-images bucket
    gsutil cp "${IMAGE_FILE}.tar.gz" "gs://${BUCKET_NAME}/"

    # Create the image in computeengine project
    delete_image "$IMAGE" "$FAMILY"
    create_image_from_bucket "$IMAGE" "$FAMILY" "$DESCRIPTION" "${IMAGE_FILE}.tar.gz"

restore: |
    rm -f "${IMAGE_FILE}.tar.gz"