summary: Add new opensuse leap 15.1 64 bits image to google account

systems: [opensuse-15.0-64-base]

environment:
    TARGET_SYSTEM: opensuse-15.1-64-base

execute: |
    . "$TESTSLIB/google.sh"
    . "$TESTSLIB/names.sh"
    . "$TESTSLIB/pkgdb.sh"
    . "$TESTSLIB/utils.sh"

    zypper addrepo --check --refresh --name 'openSUSE-Leap-15.1-Update' http://download.opensuse.org/update/leap/15.1/oss/ repo-update

    distro_update_package_db
    zypper update -y

    sed -i 's/15.0/15.1/g' /etc/zypp/repos.d/*
    zypper --gpg-auto-import-keys ref
    distro_upgrade_packages

    distro_clean_package_cache

    # Clean disk before create the shapshot
    clean_machine

    # Create the image in computeengine project
    delete_image "$IMAGE" "$FAMILY"
    create_image_from_disk "$IMAGE" "$FAMILY" "$DESCRIPTION" "$DISK"

restore: |
    . "$TESTSLIB/google.sh"
    . "$TESTSLIB/names.sh"

    delete_snapshot "$DISK"
    delete_deprecated_images
