summary: Add new debian sid image to google account

environment:
    IMAGE: debian-sid-64-v$(date +'%Y%m%d')
    FAMILY: debian-sid-64
    DESCRIPTION: Debian sid 64 bits
    DISK: $(hostname)

execute: |
    . "$TESTSLIB/google.sh"

    if ! [[ "$SPREAD_SYSTEM" == debian-* ]]; then
        echo "System used to create debian sid has to be debian"
        exit 1
    fi

    cp -a /etc/ntp.conf /var/tmp/ntp.conf.google
    apt-get update
    apt-get install -y --no-install-recommends etckeeper
    apt-get remove -y --purge ntp unattended-upgrades

    cp sources.list /tmp/sources.list

    install -m 644 -o root -g root /tmp/sources.list /etc/apt/sources.list
    apt-get update
    apt-get dist-upgrade -y --no-install-recommends --auto-remove --purge
    apt-get install -y ntp google-compute-engine
    cp -a /var/tmp/ntp.conf.google /etc/ntp.conf    
    
    # Clean disk before create the shapshot 
    apt autoremove -y
    find /var/log /var/cache/apt /var/lib/apt/{lists,mirrors} -type f -exec rm -f {} \;
    rm -rf /root/.bash_history /root/.viminfo /root/.bashrc /root/.cache

    # Project path is moved away to avoid path conflicts when this image is used with spread-images project again
    create_snapshot_from_disk "$DISK"
    delete_image "$IMAGE"
    create_image_from_snapshot "$IMAGE" "$FAMILY" "$DESCRIPTION" "$DISK"
    deprecate_old_images "$FAMILY"

restore: |
    . "$TESTSLIB/google.sh"

    delete_snapshot "$DISK"
